# Servlet configuration (Tomcat)
server:
  port: 8081

# Spring Configurations
spring:
  batch:
    initialize-schema: always

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:restdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
